name: Run Addition Program

on: [push, pull_request]

jobs:
  run-addition:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Addition Program
        run: |
          echo "5\n3" | python addition.py
